//! Diagram sources, generated from the specification.
//!
//! Every diagram is written to `docs/diagrams/<id>.<ext>` so it stands alone,
//! and embedded in `docs/midi-spec.md` from the same string, so the two cannot
//! diverge. Mermaid diagrams are inlined as a fenced block; SVG diagrams are
//! referenced with an `<img>` tag.

use std::fmt::Write as _;

use crate::spec::Spec;

/// Directory holding the standalone diagram sources, relative to the repository root.
pub const DIR: &str = "docs/diagrams";

/// What a diagram's source is written in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    /// Mermaid text, written to `.mmd` and inlined in a fenced block.
    Mermaid,
    /// An SVG document, written to `.svg` and embedded with `<img>`.
    Svg,
}

impl Kind {
    /// File extension for this kind of source.
    pub const fn extension(self) -> &'static str {
        match self {
            Self::Mermaid => "mmd",
            Self::Svg => "svg",
        }
    }
}

/// One diagram: its file stem, a title, and its source.
#[derive(Debug)]
pub struct Diagram {
    /// File stem, used for `docs/diagrams/<id>.<ext>`.
    pub id: &'static str,
    /// Title, used as the section heading in the document.
    pub title: &'static str,
    /// What `source` is written in.
    pub kind: Kind,
    /// The source, without any file header.
    pub source: String,
}

impl Diagram {
    /// The file name this diagram is written to.
    pub fn file_name(&self) -> String {
        format!("{}.{}", self.id, self.kind.extension())
    }

    /// The file contents: the source, with a header saying where it came from.
    pub fn file_contents(&self) -> String {
        match self.kind {
            Kind::Mermaid => format!(
                "%% {}\n%% Generated by `cargo xtask docs`. Edit spec/ instead.\n{}\n",
                self.title, self.source
            ),
            Kind::Svg => format!(
                "<!-- {}. Generated by `cargo xtask docs`. Edit spec/ instead. -->\n{}",
                self.title, self.source
            ),
        }
    }
}

/// Builds every diagram from the specification.
///
/// # Errors
///
/// Returns a message when a parameter group the diagrams describe is empty, or
/// when a value table they count is missing.
pub fn all(spec: &Spec) -> Result<Vec<Diagram>, String> {
    Ok(vec![
        Diagram {
            id: "signal-path",
            title: "Voice signal path",
            kind: Kind::Mermaid,
            source: signal_path(spec)?,
        },
        Diagram {
            id: "modulation-matrix",
            title: "Modulation matrix",
            kind: Kind::Mermaid,
            source: modulation_matrix(spec)?,
        },
        Diagram {
            id: "envelope",
            title: "Envelopes",
            kind: Kind::Svg,
            source: envelope(),
        },
    ])
}

/// Returns the inclusive offset range of a parameter group, as `first-last`.
fn range(spec: &Spec, group: &str) -> Result<String, String> {
    let offsets: Vec<u16> = spec
        .parameters
        .iter()
        .filter(|p| p.group == group)
        .map(|p| p.offset)
        .collect();
    match (offsets.first(), offsets.last()) {
        (Some(first), Some(last)) => Ok(format!("{first}-{last}")),
        _ => Err(format!("no parameters in group {group}")),
    }
}

/// Returns how many real choices a value table offers, discounting its Off entry.
fn choices(spec: &Spec, id: &str) -> Result<usize, String> {
    Ok(spec
        .table(id)
        .ok_or_else(|| format!("missing value table {id}"))?
        .entries
        .len()
        - 1)
}

fn signal_path(spec: &Spec) -> Result<String, String> {
    let mut out = String::from("flowchart LR\n");
    for (id, label, group) in [
        ("OSC", "OSC 1 + OSC 2<br>noise", "Oscillators"),
        ("VCF", "VCF<br>low pass", "VCF"),
        ("VCA", "VCA", "VCA"),
        ("FX", "FX<br>4 slots", "Effects"),
    ] {
        let _ = writeln!(
            out,
            "    {id}[\"{label}<br><small>{}</small>\"]",
            range(spec, group)?
        );
    }
    // The high pass and the bass boost are front-panel VCF controls but sit
    // after the VCA in the instrument, per the block diagram in section 6.
    out.push_str(
        "    HPF[\"high pass + boost<br><small>40, 52</small>\"]\n    \
         OUT([output])\n    OSC --> VCF --> VCA --> HPF --> FX --> OUT\n    \
         HPF -- analog path --> OUT\n\n",
    );
    for (id, label, group) in [
        ("VCAENV", "VCA envelope", "VCA Envelope"),
        ("VCFENV", "VCF envelope", "VCF Envelope"),
        ("MODENV", "mod envelope", "Mod Envelope"),
        ("LFO1", "LFO 1", "LFO 1"),
        ("LFO2", "LFO 2", "LFO 2"),
        ("SEQ", "control sequencer", "Control Sequencer"),
    ] {
        let _ = writeln!(
            out,
            "    {id}(\"{label}<br><small>{}</small>\")",
            range(spec, group)?
        );
    }
    let _ = writeln!(
        out,
        "    MOD{{{{\"mod matrix<br>8 busses<br><small>{}</small>\"}}}}",
        range(spec, "Mod Matrix")?
    );
    out.push_str(
        "    VCAENV -.-> VCA\n    VCFENV -.-> VCF\n    MODENV -.-> MOD\n    \
         LFO1 -.-> MOD\n    LFO2 -.-> MOD\n    SEQ -.-> MOD\n    \
         MOD -.-> OSC\n    MOD -.-> VCF\n    MOD -.-> VCA\n    MOD -.-> FX",
    );
    Ok(out)
}

fn modulation_matrix(spec: &Spec) -> Result<String, String> {
    let mut out = String::from("flowchart LR\n");
    let _ = writeln!(
        out,
        "    SRC[\"source<br><small>0 = off, {} to choose from</small>\"]",
        choices(spec, "mod_source")?
    );
    out.push_str("    DEPTH[\"depth<br><small>-128 to +127</small>\"]\n");
    let _ = writeln!(
        out,
        "    DST[\"destination<br><small>0 = off, {} to choose from</small>\"]",
        choices(spec, "mod_destination")?
    );
    out.push_str("    SRC --> DEPTH --> DST");
    Ok(out)
}

/// Where the envelope figure's plot area sits, in user units.
struct EnvelopePlot {
    left: f32,
    right: f32,
    top: f32,
    base: f32,
    sustain: f32,
    /// Where each moving stage ends, left to right: attack, decay, sustain.
    ends: [f32; 3],
}

const ENVELOPE_PLOT: EnvelopePlot = EnvelopePlot {
    left: 34.0,
    right: 306.0,
    top: 22.0,
    base: 122.0,
    sustain: 68.0,
    ends: [94.0, 154.0, 234.0],
};

const AXIS: &str = "#555";
const FAINT: &str = "#aaa";
const LINEAR: &str = "#1f6fb2";
const FAST: &str = "#c8401f";
const SLOW: &str = "#2a8f5a";

/// The four envelope stages, drawn at three curve settings.
///
/// Level against time. The key goes down at the start of the attack and comes
/// up at the end of the sustain. The linear curve is straight segments; the
/// exponential ones bend the same segments each way, one starting fast and
/// flattening out, the other starting slow and finishing fast.
fn envelope() -> String {
    let mut out = String::from(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 320 152\" width=\"640\" \
         height=\"304\" role=\"img\" aria-label=\"One envelope at three curve settings\" \
         font-family=\"ui-sans-serif, system-ui, sans-serif\" font-size=\"7\">\n\
         <title>Envelope stages</title>\n\
         <rect width=\"320\" height=\"152\" rx=\"3\" fill=\"#fafafa\"/>\n",
    );
    envelope_axes(&mut out, &ENVELOPE_PLOT);
    envelope_stages(&mut out, &ENVELOPE_PLOT);
    envelope_curves(&mut out, &ENVELOPE_PLOT);
    envelope_legend(&mut out, &ENVELOPE_PLOT);
    out.push_str("</svg>\n");
    out
}

/// The two axes, their end labels, and the key down and key up markers.
fn envelope_axes(out: &mut String, p: &EnvelopePlot) {
    let EnvelopePlot {
        left,
        right,
        top,
        base,
        ..
    } = *p;
    let _ = writeln!(
        out,
        "<line x1=\"{left}\" y1=\"{top}\" x2=\"{left}\" y2=\"{base}\" stroke=\"{AXIS}\" stroke-width=\"0.8\"/>\n\
         <line x1=\"{left}\" y1=\"{base}\" x2=\"{right}\" y2=\"{base}\" stroke=\"{AXIS}\" stroke-width=\"0.8\"/>\n\
         <text x=\"{}\" y=\"{}\" text-anchor=\"end\" fill=\"{AXIS}\">255</text>\n\
         <text x=\"{}\" y=\"{}\" text-anchor=\"end\" fill=\"{AXIS}\">0</text>\n\
         <text x=\"{left}\" y=\"{}\" text-anchor=\"middle\" fill=\"{AXIS}\" font-size=\"6.5\">level</text>\n\
         <text x=\"{right}\" y=\"{}\" text-anchor=\"end\" fill=\"{AXIS}\" font-size=\"6.5\">time</text>",
        left - 3.0,
        top + 2.5,
        left - 3.0,
        base + 2.5,
        top - 6.0,
        base + 24.0,
    );
    for (x, label, anchor) in [(left, "key down", "start"), (p.ends[2], "key up", "middle")] {
        let _ = writeln!(
            out,
            "<path d=\"M {:.1} {} L {:.1} {} L {x} {}\" fill=\"{AXIS}\"/>\n\
             <text x=\"{x}\" y=\"{}\" text-anchor=\"{anchor}\" fill=\"{AXIS}\" font-size=\"6.5\">{label}</text>",
            x - 2.5,
            base + 17.0,
            x + 2.5,
            base + 17.0,
            base + 13.0,
            base + 24.0,
        );
    }
}

/// Dashed stage boundaries, the stage names under the axis, and the sustain
/// level.
fn envelope_stages(out: &mut String, p: &EnvelopePlot) {
    let mut start = p.left;
    for (x, label) in [
        (p.ends[0], "attack"),
        (p.ends[1], "decay"),
        (p.ends[2], "sustain"),
        (p.right, "release"),
    ] {
        let _ = writeln!(
            out,
            "<line x1=\"{x}\" y1=\"{}\" x2=\"{x}\" y2=\"{}\" stroke=\"{FAINT}\" \
             stroke-width=\"0.5\" stroke-dasharray=\"2 2\"/>\n\
             <text x=\"{:.1}\" y=\"{}\" text-anchor=\"middle\" fill=\"{AXIS}\">{label}</text>",
            p.top,
            p.base,
            f32::midpoint(start, x),
            p.base + 9.0
        );
        start = x;
    }
    let _ = writeln!(
        out,
        "<line x1=\"{}\" y1=\"{}\" x2=\"{}\" y2=\"{}\" stroke=\"{FAINT}\" stroke-width=\"0.5\" \
         stroke-dasharray=\"1 2\"/>\n\
         <text x=\"{}\" y=\"{}\" fill=\"{AXIS}\" font-size=\"6.5\">sustain level</text>",
        p.left,
        p.sustain,
        p.ends[2],
        p.sustain,
        p.ends[1] + 4.0,
        p.sustain - 3.0
    );
}

/// The linear envelope as straight segments, and the two exponential ones as
/// the same segments bent each way.
fn envelope_curves(out: &mut String, p: &EnvelopePlot) {
    let EnvelopePlot {
        left,
        right,
        top,
        base,
        sustain,
        ends: [attack, decay, hold],
    } = *p;
    let _ = writeln!(
        out,
        "<polyline points=\"{left},{base} {attack},{top} {decay},{sustain} {hold},{sustain} \
         {right},{base}\" fill=\"none\" stroke=\"{LINEAR}\" stroke-width=\"1.6\" \
         stroke-linejoin=\"round\"/>"
    );
    // Each moving segment is a quadratic curve. The control point sits near
    // one end of the segment: near the start for a fast start, near the end
    // for a slow one. `along` is how far along the segment it sits, `across`
    // how far through the segment's rise or fall.
    let bend = |from: (f32, f32), to: (f32, f32), along: f32, across: f32| {
        (
            from.0 + (to.0 - from.0) * along,
            from.1 + (to.1 - from.1) * across,
        )
    };
    let start = (left, base);
    let peak = (attack, top);
    let settled = (decay, sustain);
    let released = (hold, sustain);
    let end = (right, base);
    for (colour, along, across) in [(FAST, 0.16, 0.95), (SLOW, 0.84, 0.05)] {
        let a = bend(start, peak, along, across);
        let d = bend(peak, settled, along, across);
        let r = bend(released, end, along, across);
        let _ = writeln!(
            out,
            "<path d=\"M {left} {base} Q {:.1} {:.1} {attack} {top} \
             Q {:.1} {:.1} {decay} {sustain} L {hold} {sustain} \
             Q {:.1} {:.1} {right} {base}\" fill=\"none\" stroke=\"{colour}\" \
             stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
            a.0, a.1, d.0, d.1, r.0, r.1,
        );
    }
}

fn envelope_legend(out: &mut String, p: &EnvelopePlot) {
    for (row, colour, label) in [
        (0.0, LINEAR, "linear"),
        (10.0, FAST, "exponential, fast start"),
        (20.0, SLOW, "exponential, slow start"),
    ] {
        let y = p.top + 6.0 + row;
        let _ = writeln!(
            out,
            "<line x1=\"{}\" y1=\"{y}\" x2=\"{}\" y2=\"{y}\" stroke=\"{colour}\" stroke-width=\"1.6\"/>\n\
             <text x=\"{}\" y=\"{}\" fill=\"{AXIS}\">{label}</text>",
            p.right - 88.0,
            p.right - 76.0,
            p.right - 72.0,
            y + 2.5,
        );
    }
}
