//! Diagram sources, generated from the specification.
//!
//! Every diagram is written to `docs/diagrams/<id>.<ext>` so it stands alone,
//! and embedded in `docs/midi-spec.md` from the same string, so the two cannot
//! diverge. Mermaid diagrams are inlined as a fenced block; SVG diagrams are
//! referenced with an `<img>` tag.

use std::fmt::Write as _;

use crate::spec::Spec;

/// Directory holding the standalone diagram sources, relative to the repository root.
pub const DIR: &str = "docs/diagrams";

/// What a diagram's source is written in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    /// Mermaid text, written to `.mmd` and inlined in a fenced block.
    Mermaid,
    /// An SVG document, written to `.svg` and embedded with `<img>`.
    Svg,
}

impl Kind {
    /// File extension for this kind of source.
    pub const fn extension(self) -> &'static str {
        match self {
            Self::Mermaid => "mmd",
            Self::Svg => "svg",
        }
    }
}

/// One diagram: its file stem, a title, and its source.
#[derive(Debug)]
pub struct Diagram {
    /// File stem, used for `docs/diagrams/<id>.<ext>`.
    ///
    /// Owned rather than fixed, because the cells are drawn one sheet per
    /// value table that has any and the tables are named in the specification.
    pub id: String,
    /// Title, used as the section heading in the document.
    pub title: String,
    /// What `source` is written in.
    pub kind: Kind,
    /// The source, without any file header.
    pub source: String,
}

impl Diagram {
    /// The file name this diagram is written to.
    pub fn file_name(&self) -> String {
        format!("{}.{}", self.id, self.kind.extension())
    }

    /// The file contents: the source, with a header saying where it came from.
    pub fn file_contents(&self) -> String {
        match self.kind {
            Kind::Mermaid => format!(
                "%% {}\n%% Generated by `cargo xtask docs`. Edit spec/ instead.\n{}\n",
                self.title, self.source
            ),
            Kind::Svg => format!(
                "<!-- {}. Generated by `cargo xtask docs`. Edit spec/ instead. -->\n{}",
                self.title, self.source
            ),
        }
    }
}

/// Builds every diagram from the specification.
///
/// # Errors
///
/// Returns a message when a parameter group the diagrams describe is empty, or
/// when a value table they count is missing.
pub fn all(spec: &Spec) -> Result<Vec<Diagram>, String> {
    let mut diagrams = vec![
        Diagram {
            id: "signal-path".into(),
            title: "Voice signal path".into(),
            kind: Kind::Mermaid,
            source: signal_path(spec)?,
        },
        Diagram {
            id: "modulation-matrix".into(),
            title: "Modulation matrix".into(),
            kind: Kind::Mermaid,
            source: modulation_matrix(spec)?,
        },
        Diagram {
            id: "envelope".into(),
            title: "Envelopes".into(),
            kind: Kind::Svg,
            source: envelope(),
        },
        Diagram {
            id: "marks".into(),
            title: "Effect marks".into(),
            kind: Kind::Svg,
            source: marks(spec),
        },
        Diagram {
            id: "glyphs".into(),
            title: "Parameter glyphs".into(),
            kind: Kind::Svg,
            source: glyphs(spec),
        },
    ];
    // One sheet of cells per table that has any, drawn beside that table in the
    // document, so the sources and the destinations are not one picture.
    let default = spec.default_firmware();
    for table in &spec.tables {
        if !crate::spec::Firmware::range_covers(table.firmware.as_deref(), default) {
            continue;
        }
        let drawn = cells_of(spec, table);
        if drawn.is_empty() {
            continue;
        }
        diagrams.push(Diagram {
            id: cells_id(&table.id),
            title: format!("{} cells", table.name),
            kind: Kind::Svg,
            source: sheet(&drawn, &cells_alt(table)),
        });
    }
    Ok(diagrams)
}

/// Returns the inclusive offset range of a parameter group, as `first-last`.
fn range(spec: &Spec, group: &str) -> Result<String, String> {
    let offsets: Vec<u16> = spec
        .parameters
        .iter()
        .filter(|p| p.group == group)
        .map(|p| p.offset)
        .collect();
    match (offsets.first(), offsets.last()) {
        (Some(first), Some(last)) => Ok(format!("{first}-{last}")),
        _ => Err(format!("no parameters in group {group}")),
    }
}

/// Returns how many real choices a value table offers, discounting its Off entry.
fn choices(spec: &Spec, id: &str) -> Result<usize, String> {
    Ok(spec
        .table(id)
        .ok_or_else(|| format!("missing value table {id}"))?
        .entries
        .len()
        - 1)
}

fn signal_path(spec: &Spec) -> Result<String, String> {
    let mut out = String::from("flowchart LR\n");
    for (id, label, group) in [
        ("OSC", "OSC 1 + OSC 2<br>noise", "Oscillators"),
        ("VCF", "VCF<br>low pass", "VCF"),
        ("VCA", "VCA", "VCA"),
        ("FX", "FX<br>4 slots", "Effects"),
    ] {
        let _ = writeln!(
            out,
            "    {id}[\"{label}<br><small>{}</small>\"]",
            range(spec, group)?
        );
    }
    // The high pass and the bass boost are front-panel VCF controls but sit
    // after the VCA in the instrument, per the block diagram in section 6.
    out.push_str(
        "    HPF[\"high pass + boost<br><small>40, 52</small>\"]\n    \
         OUT([output])\n    OSC --> VCF --> VCA --> HPF --> FX --> OUT\n    \
         HPF -- analog path --> OUT\n\n",
    );
    for (id, label, group) in [
        ("VCAENV", "VCA envelope", "VCA Envelope"),
        ("VCFENV", "VCF envelope", "VCF Envelope"),
        ("MODENV", "mod envelope", "Mod Envelope"),
        ("LFO1", "LFO 1", "LFO 1"),
        ("LFO2", "LFO 2", "LFO 2"),
        ("SEQ", "control sequencer", "Control Sequencer"),
    ] {
        let _ = writeln!(
            out,
            "    {id}(\"{label}<br><small>{}</small>\")",
            range(spec, group)?
        );
    }
    let _ = writeln!(
        out,
        "    MOD{{{{\"mod matrix<br>8 busses<br><small>{}</small>\"}}}}",
        range(spec, "Mod Matrix")?
    );
    out.push_str(
        "    VCAENV -.-> VCA\n    VCFENV -.-> VCF\n    MODENV -.-> MOD\n    \
         LFO1 -.-> MOD\n    LFO2 -.-> MOD\n    SEQ -.-> MOD\n    \
         MOD -.-> OSC\n    MOD -.-> VCF\n    MOD -.-> VCA\n    MOD -.-> FX",
    );
    Ok(out)
}

fn modulation_matrix(spec: &Spec) -> Result<String, String> {
    let mut out = String::from("flowchart LR\n");
    let _ = writeln!(
        out,
        "    SRC[\"source<br><small>0 = off, {} to choose from</small>\"]",
        choices(spec, "mod_source")?
    );
    out.push_str("    DEPTH[\"depth<br><small>-128 to +127</small>\"]\n");
    let _ = writeln!(
        out,
        "    DST[\"destination<br><small>0 = off, {} to choose from</small>\"]",
        choices(spec, "mod_destination")?
    );
    out.push_str("    SRC --> DEPTH --> DST");
    Ok(out)
}

/// Where the envelope figure's plot area sits, in user units.
struct EnvelopePlot {
    left: f32,
    right: f32,
    top: f32,
    base: f32,
    sustain: f32,
    /// Where each moving stage ends, left to right: attack, decay, sustain.
    ends: [f32; 3],
}

const ENVELOPE_PLOT: EnvelopePlot = EnvelopePlot {
    left: 34.0,
    right: 306.0,
    top: 22.0,
    base: 122.0,
    sustain: 68.0,
    ends: [94.0, 154.0, 234.0],
};

/// Colours that read on both backgrounds, and the two backgrounds.
///
/// Dark is the default; the light set applies when the viewer's system asks
/// for it. Text, axes and rules are classes so one stylesheet switches them.
const ENVELOPE_STYLE: &str = "\
    .bg{fill:#1b1f2a}.axis{stroke:#c9cdd6}.faint{stroke:#5a6070}.ink{fill:#c9cdd6}\n    \
    @media (prefers-color-scheme: light){\
    .bg{fill:#fafafa}.axis{stroke:#555}.faint{stroke:#aaa}.ink{fill:#555}}";
const LINEAR: &str = "#4a90d9";
const FAST: &str = "#e0563a";
const SLOW: &str = "#3fae73";

/// The four envelope stages, drawn at three curve settings.
///
/// Level against time. The key goes down at the start of the attack and comes
/// up at the end of the sustain. The linear curve is straight segments; the
/// exponential ones bend the same segments each way, one starting fast and
/// flattening out, the other starting slow and finishing fast.
fn envelope() -> String {
    let mut out = format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 320 152\" width=\"640\" \
         height=\"304\" role=\"img\" aria-label=\"One envelope at three curve settings\" \
         font-family=\"ui-sans-serif, system-ui, sans-serif\" font-size=\"7\">\n\
         <title>Envelope stages</title>\n\
         <style>\n    {ENVELOPE_STYLE}\n</style>\n\
         <rect class=\"bg\" width=\"320\" height=\"152\" rx=\"3\"/>\n",
    );
    envelope_axes(&mut out, &ENVELOPE_PLOT);
    envelope_stages(&mut out, &ENVELOPE_PLOT);
    envelope_curves(&mut out, &ENVELOPE_PLOT);
    envelope_legend(&mut out, &ENVELOPE_PLOT);
    out.push_str("</svg>\n");
    out
}

/// The two axes, their end labels, and the key down and key up markers.
fn envelope_axes(out: &mut String, p: &EnvelopePlot) {
    let EnvelopePlot {
        left,
        right,
        top,
        base,
        ..
    } = *p;
    let _ = writeln!(
        out,
        "<line class=\"axis\" x1=\"{left}\" y1=\"{top}\" x2=\"{left}\" y2=\"{base}\" stroke-width=\"0.8\"/>\n\
         <line class=\"axis\" x1=\"{left}\" y1=\"{base}\" x2=\"{right}\" y2=\"{base}\" stroke-width=\"0.8\"/>\n\
         <text class=\"ink\" x=\"{}\" y=\"{}\" text-anchor=\"end\">255</text>\n\
         <text class=\"ink\" x=\"{}\" y=\"{}\" text-anchor=\"end\">0</text>\n\
         <text class=\"ink\" x=\"{left}\" y=\"{}\" text-anchor=\"middle\" font-size=\"6.5\">level</text>\n\
         <text class=\"ink\" x=\"{right}\" y=\"{}\" text-anchor=\"end\" font-size=\"6.5\">time</text>",
        left - 3.0,
        top + 2.5,
        left - 3.0,
        base + 2.5,
        top - 6.0,
        base + 24.0,
    );
    for (x, label, anchor) in [(left, "key down", "start"), (p.ends[2], "key up", "middle")] {
        let _ = writeln!(
            out,
            "<path class=\"ink\" d=\"M {:.1} {} L {:.1} {} L {x} {}\"/>\n\
             <text class=\"ink\" x=\"{x}\" y=\"{}\" text-anchor=\"{anchor}\" font-size=\"6.5\">{label}</text>",
            x - 2.5,
            base + 17.0,
            x + 2.5,
            base + 17.0,
            base + 13.0,
            base + 24.0,
        );
    }
}

/// Dashed stage boundaries, the stage names under the axis, and the sustain
/// level.
fn envelope_stages(out: &mut String, p: &EnvelopePlot) {
    let mut start = p.left;
    for (x, label) in [
        (p.ends[0], "attack"),
        (p.ends[1], "decay"),
        (p.ends[2], "sustain"),
        (p.right, "release"),
    ] {
        let _ = writeln!(
            out,
            "<line class=\"faint\" x1=\"{x}\" y1=\"{}\" x2=\"{x}\" y2=\"{}\" \
             stroke-width=\"0.5\" stroke-dasharray=\"2 2\"/>\n\
             <text class=\"ink\" x=\"{:.1}\" y=\"{}\" text-anchor=\"middle\">{label}</text>",
            p.top,
            p.base,
            f32::midpoint(start, x),
            p.base + 9.0
        );
        start = x;
    }
    let _ = writeln!(
        out,
        "<line class=\"faint\" x1=\"{}\" y1=\"{}\" x2=\"{}\" y2=\"{}\" stroke-width=\"0.5\" \
         stroke-dasharray=\"1 2\"/>\n\
         <text class=\"ink\" x=\"{}\" y=\"{}\" font-size=\"6.5\">sustain level</text>",
        p.left,
        p.sustain,
        p.ends[2],
        p.sustain,
        p.ends[1] + 4.0,
        p.sustain - 3.0
    );
}

/// The linear envelope as straight segments, and the two exponential ones as
/// the same segments bent each way.
fn envelope_curves(out: &mut String, p: &EnvelopePlot) {
    let EnvelopePlot {
        left,
        right,
        top,
        base,
        sustain,
        ends: [attack, decay, hold],
    } = *p;
    let _ = writeln!(
        out,
        "<polyline points=\"{left},{base} {attack},{top} {decay},{sustain} {hold},{sustain} \
         {right},{base}\" fill=\"none\" stroke=\"{LINEAR}\" stroke-width=\"1.6\" \
         stroke-linejoin=\"round\"/>"
    );
    // Each moving segment is a quadratic curve. The control point sits near
    // one end of the segment: near the start for a fast start, near the end
    // for a slow one. `along` is how far along the segment it sits, `across`
    // how far through the segment's rise or fall.
    let bend = |from: (f32, f32), to: (f32, f32), along: f32, across: f32| {
        (
            from.0 + (to.0 - from.0) * along,
            from.1 + (to.1 - from.1) * across,
        )
    };
    let start = (left, base);
    let peak = (attack, top);
    let settled = (decay, sustain);
    let released = (hold, sustain);
    let end = (right, base);
    for (colour, along, across) in [(FAST, 0.16, 0.95), (SLOW, 0.84, 0.05)] {
        let a = bend(start, peak, along, across);
        let d = bend(peak, settled, along, across);
        let r = bend(released, end, along, across);
        let _ = writeln!(
            out,
            "<path d=\"M {left} {base} Q {:.1} {:.1} {attack} {top} \
             Q {:.1} {:.1} {decay} {sustain} L {hold} {sustain} \
             Q {:.1} {:.1} {right} {base}\" fill=\"none\" stroke=\"{colour}\" \
             stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
            a.0, a.1, d.0, d.1, r.0, r.1,
        );
    }
}

fn envelope_legend(out: &mut String, p: &EnvelopePlot) {
    for (row, colour, label) in [
        (0.0, LINEAR, "linear"),
        (10.0, FAST, "exponential, fast start"),
        (20.0, SLOW, "exponential, slow start"),
    ] {
        let y = p.top + 6.0 + row;
        let _ = writeln!(
            out,
            "<line x1=\"{}\" y1=\"{y}\" x2=\"{}\" y2=\"{y}\" stroke=\"{colour}\" stroke-width=\"1.6\"/>\n\
             <text class=\"ink\" x=\"{}\" y=\"{}\">{label}</text>",
            p.right - 88.0,
            p.right - 76.0,
            p.right - 72.0,
            y + 2.5,
        );
    }
}

/// The nine family marks, each drawn both ways at the sizes they are for.
///
/// A proof rather than an illustration. The strokes drawn here are the ones the
/// library publishes, straight out of `spec/marks.toml` with nothing added, and
/// the pixel grids below them are the same bits a host blits. A mark that reads
/// badly here reads badly in a host too, which is how three of these came to be
/// redrawn.
fn marks(spec: &Spec) -> String {
    /// Side of the large stroked mark, in the SVG's own units.
    const LARGE: f32 = 54.0;
    /// Side of the small stroked mark, about what a panel header gives one.
    const SMALL: f32 = 16.0;
    /// Side of a pixel in the magnified grid.
    const PIXEL: f32 = 6.0;
    /// Space around each column.
    const PAD: f32 = 16.0;

    /// Marks per row: the nine families make the first row, and the variants
    /// wrap under them at the same pitch.
    const ACROSS: usize = 9;

    let side = count(crate::spec::PIXEL_SIDE);
    let grid = side * PIXEL;
    let column = LARGE.max(grid);
    let pitch = column + PAD;
    let width = pitch * count(ACROSS) + PAD;

    // Every mark, the families first and then the variants, each as a name
    // and the two drawings of it.
    let marks: Vec<(&str, &[crate::spec::Stroke], &[String])> = spec
        .families
        .iter()
        .map(|f| (f.name.as_str(), f.strokes.as_slice(), f.pixels.as_slice()))
        .chain(
            spec.variants
                .iter()
                .map(|v| (v.name.as_str(), v.strokes.as_slice(), v.pixels.as_slice())),
        )
        .collect();
    let rows = spec.families.len().div_ceil(ACROSS) + spec.variants.len().div_ceil(ACROSS);

    let small_gap = LARGE + 10.0;
    let grid_gap = small_gap + SMALL + 14.0;
    let true_gap = grid_gap + grid + 10.0;
    let label_gap = true_gap + side + 14.0;
    let row_height = label_gap + PAD;
    let height = PAD + row_height * count(rows);

    let mut out = format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 {width} {height}\" \
         width=\"{width}\" height=\"{height}\" role=\"img\" \
         aria-label=\"{MARKS_ALT}\">\n\
         <style>\n\
         .mark {{ fill: none; stroke: #2b2f38; stroke-width: 2; stroke-linecap: round; \
         stroke-linejoin: round; }}\n\
         .mark .dot {{ fill: #2b2f38; stroke: none; }}\n\
         .small {{ stroke-width: 1.4; }}\n\
         .lit {{ fill: #2b2f38; }}\n\
         .unlit {{ fill: #e7e9ed; }}\n\
         .name {{ font: 500 9px system-ui, sans-serif; fill: #6b7280; text-anchor: middle; }}\n\
         @media (prefers-color-scheme: dark) {{\n\
         .mark {{ stroke: #d8dbe2; }}\n\
         .mark .dot {{ fill: #d8dbe2; }}\n\
         .lit {{ fill: #d8dbe2; }}\n\
         .unlit {{ fill: #31353d; }}\n\
         .name {{ fill: #9aa2b1; }}\n\
         }}\n\
         </style>\n"
    );

    for (index, (name, strokes, pixels)) in marks.iter().enumerate() {
        // The variants start a new row under the families, whatever is left
        // of the families' last one.
        let (column_index, row) = if index < spec.families.len() {
            (index % ACROSS, index / ACROSS)
        } else {
            let offset = index - spec.families.len();
            (
                offset % ACROSS,
                spec.families.len().div_ceil(ACROSS) + offset / ACROSS,
            )
        };
        let left = PAD + pitch * count(column_index);
        let centre = left + column / 2.0;
        let stroked_top = PAD + row_height * count(row);
        let small_top = stroked_top + small_gap;
        let grid_top = stroked_top + grid_gap;
        let true_top = stroked_top + true_gap;
        let label_top = stroked_top + label_gap;

        let _ = write!(
            out,
            "  <g class=\"mark\">\n{}  </g>\n",
            draw_mark(strokes, centre - LARGE / 2.0, stroked_top, LARGE)
        );
        let _ = write!(
            out,
            "  <g class=\"mark small\">\n{}  </g>\n",
            draw_mark(strokes, centre - SMALL / 2.0, small_top, SMALL)
        );

        // The grid magnified, so the placement can be read, and again at one
        // pixel per pixel, which is the size it is actually for.
        draw_grid(
            &mut out,
            pixels,
            PIXEL,
            (centre - grid / 2.0, grid_top),
            (centre - side / 2.0, true_top),
        );

        let _ = writeln!(
            out,
            "  <text class=\"name\" x=\"{centre:.1}\" y=\"{label_top:.1}\">{name}</text>",
        );
    }
    out.push_str("</svg>\n");
    out
}

/// The alt text of the marks drawing, shared with the document that embeds it.
pub const MARKS_ALT: &str =
    "The nine effect family marks and the variants under them, as strokes and as pixels";

/// The file stem of the sheet of cells drawn for a value table.
#[must_use]
pub fn cells_id(table: &str) -> String {
    format!("cells-{}", table.replace('_', "-"))
}

/// The alt text of a table's cells drawing, shared with the document that
/// embeds it.
#[must_use]
pub fn cells_alt(table: &crate::spec::ValueTable) -> String {
    format!(
        "The {} cells, magnified and at one dot per dot",
        table.name.to_lowercase()
    )
}

/// The cells drawn for a table, in the order its entries are listed, each with
/// the name of the entry it is drawn for.
///
/// The same proof the marks drawing is: these are the bits a host blits,
/// straight out of `spec/cells.toml`, so a cell that reads badly in the sheet
/// reads badly in a host too.
fn cells_of<'a>(
    spec: &'a Spec,
    table: &'a crate::spec::ValueTable,
) -> Vec<(&'a str, &'a [String])> {
    table
        .entries
        .iter()
        .filter_map(|entry| {
            let cell = spec.cell_for(table, entry)?;
            Some((entry.name.as_str(), cell.pixels.as_slice()))
        })
        .collect()
}

/// Cells per row of the cells drawing.
const CELLS_ACROSS: usize = 10;

/// Side of a magnified dot in the cells drawing, in the SVG's own units.
const CELL_DOT: usize = 6;

/// Space around each column of the cells drawing.
const CELL_PAD: usize = 16;

/// Returns the width a sheet of `drawn` cells is rendered at, for the `<img>`
/// that embeds it.
///
/// Integer arithmetic on the same numbers [`sheet`] lays the drawing out with,
/// so the two cannot disagree by a rounding.
#[must_use]
pub fn cells_width(drawn: usize) -> usize {
    let pitch = crate::spec::PIXEL_SIDE * CELL_DOT + CELL_PAD;
    pitch * drawn.min(CELLS_ACROSS) + CELL_PAD
}

/// The alt text of the glyphs drawing, shared with the document that embeds it.
pub const GLYPHS_ALT: &str = "The parameter glyphs, magnified and at one dot per dot";

/// Returns the width the glyphs drawing is rendered at, as [`cells_width`].
pub fn glyphs_width(spec: &Spec) -> usize {
    let pitch = crate::spec::PIXEL_SIDE * CELL_DOT + CELL_PAD;
    pitch * spec.glyphs.len().min(CELLS_ACROSS) + CELL_PAD
}

/// Draws every glyph, magnified and at one dot per dot, with its name.
fn glyphs(spec: &Spec) -> String {
    let items: Vec<(&str, &[String])> = spec
        .glyphs
        .iter()
        .map(|glyph| (glyph.name.as_str(), glyph.pixels.as_slice()))
        .collect();
    sheet(&items, GLYPHS_ALT)
}

/// Draws a sheet of pixel grids, [`CELLS_ACROSS`] to a row, each magnified
/// and again at one dot per dot, with its name under it.
fn sheet(items: &[(&str, &[String])], alt: &str) -> String {
    let side = count(crate::spec::PIXEL_SIDE);
    let dot = count(CELL_DOT);
    let pad = count(CELL_PAD);
    let grid = side * dot;
    let pitch = grid + pad;
    let rows = items.len().div_ceil(CELLS_ACROSS);
    let width =
        (crate::spec::PIXEL_SIDE * CELL_DOT + CELL_PAD) * items.len().min(CELLS_ACROSS) + CELL_PAD;

    let true_gap = 10.0;
    let label_gap = 14.0;
    let row_height = grid + true_gap + side + label_gap + pad;
    let height = pad + row_height * count(rows);

    let mut out = format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 {width} {height}\" \
         width=\"{width}\" height=\"{height}\" role=\"img\" aria-label=\"{alt}\">\n\
         <style>\n\
         .lit {{ fill: #2b2f38; }}\n\
         .unlit {{ fill: #e7e9ed; }}\n\
         .name {{ font: 500 9px system-ui, sans-serif; fill: #6b7280; text-anchor: middle; }}\n\
         @media (prefers-color-scheme: dark) {{\n\
         .lit {{ fill: #d8dbe2; }}\n\
         .unlit {{ fill: #31353d; }}\n\
         .name {{ fill: #9aa2b1; }}\n\
         }}\n\
         </style>\n"
    );

    for (index, (name, pixels)) in items.iter().enumerate() {
        let column = index % CELLS_ACROSS;
        let row = index / CELLS_ACROSS;
        let left = pad + pitch * count(column);
        let centre = left + grid / 2.0;
        let grid_top = pad + row_height * count(row);
        let true_top = grid_top + grid + true_gap;
        let label_top = true_top + side + label_gap;
        // On whole units, so the one-dot rectangles land on pixels rather
        // than straddling two of them.
        let true_left = (centre - side / 2.0).round();

        draw_grid(
            &mut out,
            pixels,
            dot,
            (left, grid_top),
            (true_left, true_top),
        );
        let _ = writeln!(
            out,
            "  <text class=\"name\" x=\"{centre:.1}\" y=\"{label_top:.1}\">{}</text>",
            name.replace('&', "&amp;"),
        );
    }
    out.push_str("</svg>\n");
    out
}

/// Draws a pixel grid twice: magnified to `dot` per pixel at `magnified`, and
/// at one unit per pixel at `actual`, which is the size it is for.
fn draw_grid(
    out: &mut String,
    pixels: &[String],
    dot: f32,
    magnified: (f32, f32),
    actual: (f32, f32),
) {
    for (y, row) in pixels.iter().enumerate() {
        for (x, pixel) in row.chars().enumerate() {
            let class = if pixel == '#' { "lit" } else { "unlit" };
            let _ = writeln!(
                out,
                "  <rect class=\"{class}\" x=\"{:.1}\" y=\"{:.1}\" \
                 width=\"{:.1}\" height=\"{:.1}\" />",
                magnified.0 + count(x) * dot,
                magnified.1 + count(y) * dot,
                dot - 1.0,
                dot - 1.0,
            );
            if pixel == '#' {
                let _ = writeln!(
                    out,
                    "  <rect class=\"lit\" x=\"{:.1}\" y=\"{:.1}\" width=\"1\" \
                     height=\"1\" />",
                    actual.0 + count(x),
                    actual.1 + count(y),
                );
            }
        }
    }
}

/// Returns a count as a length. The counts here are families, pixels and
/// columns, so a byte holds every value one can take.
fn count(of: usize) -> f32 {
    f32::from(u8::try_from(of).unwrap_or(u8::MAX))
}

/// Draws one mark's strokes, scaling the unit box to `side` at `(left, top)`.
fn draw_mark(strokes: &[crate::spec::Stroke], left: f32, top: f32, side: f32) -> String {
    let at = |x: f32, y: f32| (left + x * side, top + y * side);
    let mut out = String::new();
    for stroke in strokes {
        if let Some(points) = &stroke.line {
            let drawn: Vec<String> = points
                .iter()
                .map(|&[x, y]| {
                    let (x, y) = at(x, y);
                    format!("{x:.2},{y:.2}")
                })
                .collect();
            let _ = writeln!(out, "    <polyline points=\"{}\" />", drawn.join(" "));
        } else if let Some(wave) = &stroke.wave {
            // Sampled, because that is what the published curve is for. The
            // count is this drawing's business and nobody else's: enough that
            // the segments are shorter than a stroke width at the size drawn.
            // A step count, not a step size, so that the same curve is drawn
            // at whatever resolution this size deserves. Kept in a byte so
            // there is no cast between a count and a length.
            let samples: u8 = if side > 32.0 { 192 } else { 64 };
            let (dx, dy) = (wave.end[0] - wave.start[0], wave.end[1] - wave.start[1]);
            let length = dx.hypot(dy).max(f32::EPSILON);
            let (nx, ny) = (dy / length, -dx / length);
            let drawn: Vec<String> = (0..=samples)
                .map(|step| {
                    let u = f32::from(step) / f32::from(samples);
                    let offset = wave.amplitude * (u * wave.cycles * core::f32::consts::TAU).sin();
                    let (x, y) = at(
                        wave.start[0] + dx * u + nx * offset,
                        wave.start[1] + dy * u + ny * offset,
                    );
                    format!("{x:.2},{y:.2}")
                })
                .collect();
            let _ = writeln!(out, "    <polyline points=\"{}\" />", drawn.join(" "));
        } else if let Some(dot) = &stroke.dot {
            let (cx, cy) = at(dot.centre[0], dot.centre[1]);
            let _ = writeln!(
                out,
                "    <circle class=\"dot\" cx=\"{cx:.2}\" cy=\"{cy:.2}\" r=\"{:.2}\" />",
                dot.radius * side,
            );
        } else if let Some(arc) = &stroke.arc {
            let (cx, cy) = at(arc.centre[0], arc.centre[1]);
            let radius = arc.radius * side;
            // Turns clockwise from three o'clock, in a box with y downward, so
            // the angle goes straight into cos/sin with no sign to flip.
            let point = |turns: f32| {
                let radians = turns * core::f32::consts::TAU;
                (cx + radius * radians.cos(), cy + radius * radians.sin())
            };
            // A whole turn has the same two endpoints, which an arc command
            // cannot draw; a circle is what it means.
            if arc.sweep.abs() >= 1.0 {
                let _ = writeln!(
                    out,
                    "    <circle cx=\"{cx:.2}\" cy=\"{cy:.2}\" r=\"{radius:.2}\" />"
                );
                continue;
            }
            let (x0, y0) = point(arc.start);
            let (x1, y1) = point(arc.start + arc.sweep);
            let large = u8::from(arc.sweep.abs() > 0.5);
            let sweep = u8::from(arc.sweep > 0.0);
            let _ = writeln!(
                out,
                "    <path d=\"M {x0:.2} {y0:.2} A {radius:.2} {radius:.2} 0 {large} {sweep} \
                 {x1:.2} {y1:.2}\" />"
            );
        }
    }
    out
}
