//! Generates the reference tables in `docs/midi-spec.md` from `spec/`.
//!
//! Prose in that file is written by hand. Tables live between marker comments
//! and are owned by this module:
//!
//! ```text
//! <!-- generated:parameters -->
//! ...replaced on every run...
//! <!-- /generated:parameters -->
//! ```
//!
//! `cargo xtask docs` rewrites the marked regions; `cargo xtask docs --check`
//! reports staleness without touching the file. The `generated_documentation_is_current`
//! test runs the same comparison, so a stale checkout fails `cargo test`.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::diagrams;
use crate::spec::Spec;

/// Path of the document this module owns, relative to the repository root.
pub const DOC_PATH: &str = "docs/midi-spec.md";

/// Outcome of a generation run.
#[derive(Debug, PartialEq, Eq)]
pub enum Outcome {
    /// The file on disk already matched.
    Current,
    /// The file differed. It was rewritten unless the run was a check.
    Stale,
}

/// Renders the marked regions and compares them against the file on disk.
///
/// Writes the result unless `check` is set.
///
/// # Errors
///
/// Returns a message when the spec cannot be loaded, the document is missing,
/// a marker pair is missing or malformed, or the file cannot be written.
pub fn run(root: &Path, check: bool) -> Result<Outcome, String> {
    let spec = Spec::load(root)?;
    let diagrams = diagrams::all(&spec)?;
    let mut stale = write_diagram_sources(root, &diagrams, check)?;
    let path: PathBuf = root.join(DOC_PATH);
    let current = std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;

    let mut updated = current.clone();
    for (marker, body) in [
        ("structure", render_structure(&spec, &diagrams)?),
        ("messages", render_messages(&spec)),
        ("parameters", render_parameters(&spec)),
        ("firmware", render_firmware(&spec)),
        ("mapping", render_mapping(&spec)),
        ("value-tables", render_value_tables(&spec)),
        ("globals", render_globals(&spec)),
        ("controllers", render_controllers(&spec)),
        ("effects", render_effects(&spec)),
        ("corrections", render_corrections(&spec)),
    ] {
        updated = splice(&updated, marker, &body)?;
    }

    if updated != current {
        stale = true;
        if !check {
            std::fs::write(&path, updated).map_err(|e| format!("{}: {e}", path.display()))?;
        }
    }
    Ok(if stale {
        Outcome::Stale
    } else {
        Outcome::Current
    })
}

/// Writes each diagram to `docs/diagrams/<id>.mmd`, or reports staleness.
///
/// Returns whether any file differed from what is on disk.
fn write_diagram_sources(
    root: &Path,
    all: &[diagrams::Diagram],
    check: bool,
) -> Result<bool, String> {
    let dir = root.join(diagrams::DIR);
    if !check {
        std::fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    }

    let mut stale = false;
    for diagram in all {
        let path = dir.join(format!("{}.mmd", diagram.id));
        let wanted = format!(
            "%% {}\n%% Generated by `cargo xtask docs`. Edit spec/ instead.\n{}\n",
            diagram.title, diagram.source
        );
        if std::fs::read_to_string(&path).is_ok_and(|found| found == wanted) {
            continue;
        }
        stale = true;
        if !check {
            std::fs::write(&path, &wanted).map_err(|e| format!("{}: {e}", path.display()))?;
        }
    }
    Ok(stale)
}

/// Replaces the text between `<!-- generated:NAME -->` and `<!-- /generated:NAME -->`.
fn splice(document: &str, marker: &str, body: &str) -> Result<String, String> {
    let open = format!("<!-- generated:{marker} -->");
    let close = format!("<!-- /generated:{marker} -->");
    let start = document
        .find(&open)
        .ok_or_else(|| format!("{DOC_PATH}: missing marker {open}"))?
        + open.len();
    let end = document
        .find(&close)
        .ok_or_else(|| format!("{DOC_PATH}: missing marker {close}"))?;
    if end < start {
        return Err(format!("{DOC_PATH}: marker {close} precedes {open}"));
    }
    Ok(format!(
        "{}\n\n{}\n\n{}",
        &document[..start],
        body.trim(),
        &document[end..]
    ))
}

/// Escapes the characters that would otherwise break out of a table cell.
fn cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

/// Renders the structure section: each diagram inline, with the prose around it.
///
/// The Mermaid sources are the same strings written to `docs/diagrams`, so the
/// document and the standalone sources always agree.
///
/// # Errors
///
/// Returns a message when a diagram is missing from the generated set.
fn render_structure(spec: &Spec, all: &[diagrams::Diagram]) -> Result<String, String> {
    let source = |id: &str| -> Result<&str, String> {
        all.iter()
            .find(|d| d.id == id)
            .map(|d| d.source.as_str())
            .ok_or_else(|| format!("missing diagram {id}"))
    };
    let title = |id: &str| -> Result<&str, String> {
        all.iter()
            .find(|d| d.id == id)
            .map(|d| d.title)
            .ok_or_else(|| format!("missing diagram {id}"))
    };

    let mut out = String::new();
    let _ = writeln!(out, "### {}\n", title("signal-path")?);
    out.push_str(
        "Each block is a parameter group, labelled with its offsets. Solid \
                  arrows carry audio, dashed arrows carry modulation.\n\n",
    );
    let _ = writeln!(out, "```mermaid\n{}\n```\n", source("signal-path")?);

    let _ = writeln!(out, "### {}\n", title("modulation-matrix")?);
    out.push_str("Eight independent busses, each a source, a destination and a signed depth.\n\n");
    let _ = writeln!(out, "```mermaid\n{}\n```\n", source("modulation-matrix")?);

    let mut busses = spec
        .parameters
        .iter()
        .filter(|p| p.group == "Mod Matrix")
        .map(|p| p.offset);
    let first = busses.next().unwrap_or(0);
    let _ = writeln!(
        out,
        "Each bus occupies three consecutive offsets: source, destination, depth. \
         Bus 1 is {first}, {}, {}, and bus 8 is {}, {}, {}.\n",
        first + 1,
        first + 2,
        first + 21,
        first + 22,
        first + 23
    );

    let _ = writeln!(out, "### {}\n", title("envelope")?);
    out.push_str(
        "Three identical envelopes: VCA, VCF and mod. Each has the four \
                  familiar stages plus a curve control per stage, which bends the \
                  segment between linear and exponential.\n\n",
    );
    let _ = writeln!(out, "```mermaid\n{}\n```\n", source("envelope")?);
    out.push_str(
        "| Stage | VCA | VCF | Mod |\n|---|---|---|---|\n\
                  | Attack time | 53 | 62 | 71 |\n\
                  | Decay time | 54 | 63 | 72 |\n\
                  | Sustain level | 55 | 64 | 73 |\n\
                  | Release time | 56 | 65 | 74 |\n\
                  | Attack curve | 58 | 67 | 76 |\n\
                  | Decay curve | 59 | 68 | 77 |\n\
                  | Sustain curve | 60 | 69 | 78 |\n\
                  | Release curve | 61 | 70 | 79 |\n",
    );

    Ok(out)
}

fn render_messages(spec: &Spec) -> String {
    let mut out = String::from("| Cmd | Message | Direction | Payload | Raw | Packed |\n");
    out.push_str("|---|---|---|---|---|---|\n");
    for message in &spec.messages {
        let direction = if message.direction == "to_device" {
            "host to synth"
        } else {
            "synth to host"
        };
        let raw = message.raw_len.map_or_else(String::new, |n| n.to_string());
        let packed = message
            .packed_len
            .map_or_else(String::new, |n| n.to_string());
        let _ = writeln!(
            out,
            "| `{:02X}` | {} | {direction} | {} | {raw} | {packed} |",
            message.command,
            cell(&message.name),
            cell(message.payload.as_deref().unwrap_or("none")),
        );
    }

    let notes: Vec<&crate::spec::Message> =
        spec.messages.iter().filter(|m| m.note.is_some()).collect();
    if !notes.is_empty() {
        out.push('\n');
        for message in notes {
            let note = message.note.as_deref().unwrap_or_default().trim();
            let _ = writeln!(out, "**{}.** {note}\n", message.name);
        }
    }
    out
}

fn render_parameters(spec: &Spec) -> String {
    let mut out = String::new();
    let mut group = "";
    for parameter in &spec.parameters {
        if parameter.group != group {
            group = &parameter.group;
            let _ = write!(
                out,
                "\n### {group}\n\n| Offset | Parameter | Raw | Values | Shows as |\n\
                 |---|---|---|---|---|\n"
            );
        }
        let values = match (&parameter.kind, &parameter.value_table, &parameter.note) {
            (Some(kind), _, _) if kind == "switch" => "Off (0), On (1)".to_owned(),
            (_, Some(id), _) => {
                let name = spec.table(id).map_or(id.as_str(), |t| t.name.as_str());
                format!("[{name}](#{id})")
            }
            (_, _, Some(note)) => cell(note),
            _ => String::new(),
        };
        let values = if parameter.confirmed {
            values
        } else {
            format!("**Unconfirmed.** {values}")
        };
        let _ = writeln!(
            out,
            "| {} | {} | {}-{} | {values} | {} |",
            parameter.offset,
            cell(&parameter.name),
            parameter.min,
            parameter.max,
            cell(parameter.display.as_deref().unwrap_or(""))
        );
    }
    out
}

/// Renders each transport's byte pattern, its fields, and the encodings.
fn render_mapping(spec: &Spec) -> String {
    let mut out = String::new();
    for transport in &spec.transports {
        let _ = write!(
            out,
            "\n### {}\n\n{}\n\n```\n{}\n```\n\n",
            cell(&transport.name),
            transport.summary,
            transport.pattern
        );
        if let Some(note) = &transport.note {
            let _ = write!(out, "{note}\n\n");
        }
        out.push_str("| Field | From | Encoding | Bits | Notes |\n|---|---|---|---|---|\n");
        for field in &transport.fields {
            let note = cell(field.note.as_deref().unwrap_or(""));
            let notes = if field.optional {
                let when = cell(field.optional_when.as_deref().unwrap_or(""));
                format!("Optional. {when} {note}").trim().to_owned()
            } else {
                note
            };
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | {} | {notes} |",
                cell(&field.name),
                cell(&field.source),
                field
                    .encoding
                    .as_deref()
                    .map_or_else(|| "-".to_owned(), |id| format!("[{id}](#encodings)")),
                field.bits.map_or_else(|| "-".to_owned(), |b| b.to_string()),
            );
        }
    }

    out.push_str("\n<a id=\"encodings\"></a>\n\n### Encodings\n\n");
    out.push_str("| Encoding | Name | Rule | Notes |\n|---|---|---|---|\n");
    for encoding in &spec.encodings {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} |",
            cell(&encoding.id),
            cell(&encoding.name),
            cell(&encoding.rule),
            cell(encoding.note.as_deref().unwrap_or(""))
        );
    }
    out
}

/// Renders the firmware list and what each version changed.
fn render_firmware(spec: &Spec) -> String {
    let default = spec.default_firmware();
    let mut out = String::from("| Version | Notes |\n|---|---|\n");
    for firmware in &spec.firmwares {
        let marker = if firmware.version == default {
            " (assumed by default)"
        } else {
            ""
        };
        let _ = writeln!(
            out,
            "| {}{marker} | {} |",
            cell(&firmware.version),
            cell(firmware.note.as_deref().unwrap_or(""))
        );
    }
    out
}

/// Anchor for a value table, kept unique when firmware split it in two.
fn table_anchor(table: &crate::spec::ValueTable, default: &str) -> String {
    match &table.firmware {
        Some(range) if !crate::spec::Firmware::range_covers(Some(range), default) => {
            format!("{}-fw{}", table.id, range.replace(['.', '+'], ""))
        }
        _ => table.id.clone(),
    }
}

fn render_value_tables(spec: &Spec) -> String {
    let default = spec.default_firmware();
    let mut out = String::new();
    for table in &spec.tables {
        let _ = write!(
            out,
            "\n<a id=\"{}\"></a>\n\n#### {}\n\n",
            table_anchor(table, default),
            table.name
        );
        if let Some(range) = &table.firmware {
            let _ = write!(out, "Firmware {range}.\n\n");
        }
        if let Some(note) = &table.note {
            let _ = write!(out, "{note}\n\n");
        }
        if !table.confirmed {
            out.push_str(
                "> Unconfirmed. This mapping is inferred and needs checking against hardware.\n\n",
            );
        }
        out.push_str("| Value | Name | Notes |\n|---|---|---|\n");
        for entry in &table.entries {
            let _ = writeln!(
                out,
                "| {} | {} | {} |",
                entry.value,
                cell(&entry.name),
                cell(entry.description.as_deref().unwrap_or(""))
            );
        }
    }
    out
}

fn render_globals(spec: &Spec) -> String {
    let mut out = String::from("| Setting | Range | Notes |\n|---|---|---|\n");
    for global in &spec.globals {
        let mut notes = cell(global.note.as_deref().unwrap_or(""));
        if !global.confirmed {
            notes = format!("**Unconfirmed.** {notes}");
        }
        let _ = writeln!(
            out,
            "| {} | {}-{} | {notes} |",
            cell(&global.name),
            global.min,
            global.max
        );
    }
    out
}

fn render_controllers(spec: &Spec) -> String {
    let mut out = String::new();
    for (kind, heading, blurb) in [
        (
            "parameter",
            "Program parameters",
            "Each of these drives one program parameter. The offset column is that \
             parameter's entry in the table above.",
        ),
        (
            "standard",
            "Standard controllers",
            "Ordinary MIDI controllers, answered in the usual way.",
        ),
        (
            "other",
            "Everything else",
            "Controllers that do something but are not a single program parameter.",
        ),
    ] {
        let rows: Vec<&crate::spec::Controller> =
            spec.controllers.iter().filter(|c| c.kind == kind).collect();
        if rows.is_empty() {
            continue;
        }

        let _ = write!(out, "\n#### {heading}\n\n{blurb}\n\n| CC | Controls |");
        if kind == "parameter" {
            out.push_str(" Offset |");
        }
        out.push_str(" Notes |\n|---|---|");
        if kind == "parameter" {
            out.push_str("---|");
        }
        out.push_str("---|\n");

        for controller in rows {
            let mut notes = cell(controller.note.as_deref().unwrap_or(""));
            if !controller.confirmed {
                notes = format!("**Unconfirmed.** {notes}");
            }
            let _ = write!(out, "| {} | {} |", controller.cc, cell(&controller.name));
            if kind == "parameter" {
                let _ = write!(
                    out,
                    " {} |",
                    controller
                        .parameter
                        .map_or_else(|| "-".to_owned(), |o| o.to_string())
                );
            }
            let _ = writeln!(out, " {notes} |");
        }
    }
    out
}

/// Renders one table per algorithm: what each of an engine's twelve raw
/// parameters means when that algorithm is loaded.
fn render_effects(spec: &Spec) -> String {
    let mut out = String::new();
    for effect in &spec.effects {
        let _ = write!(
            out,
            "\n<a id=\"fx-{}\"></a>\n\n#### {} ({})\n\n`FX Type` {}.\n\n\
             | Slot | Ref | Parameter | Control | Group | Range | Mod | \
             Description |\n|---|---|---|---|---|---|---|---|\n",
            effect.r#type,
            cell(&effect.full_name),
            cell(&effect.name),
            effect.r#type,
        );
        let panel = spec.panels.iter().find(|p| p.r#type == effect.r#type);
        for parameter in &effect.parameters {
            let slot = panel.and_then(|p| p.slots.iter().find(|s| s.slot == parameter.slot));
            let range = match (&parameter.values, &parameter.min, &parameter.max) {
                (Some(values), _, _) => cell(values),
                (_, Some(min), Some(max)) => {
                    let unit = parameter.unit.as_deref().unwrap_or("");
                    let unit = if unit.is_empty() {
                        String::new()
                    } else {
                        format!(" {unit}")
                    };
                    format!("{min} to {max}{unit}")
                }
                _ => String::new(),
            };
            let range = match &parameter.note {
                Some(note) => format!("{range}. {}", cell(note)),
                None => range,
            };
            let _ = writeln!(
                out,
                "| {} | `{}` | {} | {} | {} | {range} | {} | {} |",
                parameter.slot,
                cell(&parameter.r#ref),
                cell(&parameter.name),
                slot.map_or("", |s| s.kind.as_str()),
                slot.and_then(|s| s.group.as_deref()).unwrap_or(""),
                if parameter.mod_dest { "yes" } else { "" },
                cell(parameter.description.as_deref().unwrap_or(""))
            );
        }
    }
    out
}

fn render_corrections(spec: &Spec) -> String {
    // Several corrections apply identically to every slot of a repeated group,
    // such as the eight modulation matrix busses, so rows are grouped by text.
    let mut groups: Vec<(&str, Vec<&crate::spec::Parameter>)> = Vec::new();
    for parameter in &spec.parameters {
        let Some(correction) = parameter.correction.as_deref() else {
            continue;
        };
        match groups.iter_mut().find(|(text, _)| *text == correction) {
            Some((_, members)) => members.push(parameter),
            None => groups.push((correction, vec![parameter])),
        }
    }
    if groups.is_empty() {
        return "None recorded.".to_owned();
    }

    let mut out = String::from("| Offsets | Parameter | Correction |\n|---|---|---|\n");
    for (correction, members) in groups {
        let offsets = if members.len() <= 8 {
            members
                .iter()
                .map(|p| p.offset.to_string())
                .collect::<Vec<_>>()
                .join(", ")
        } else {
            format!(
                "{} values from {} to {}",
                members.len(),
                members[0].offset,
                members[members.len() - 1].offset
            )
        };
        let name = match members.as_slice() {
            [only] => cell(&only.name),
            _ => format!("{} and {} more", cell(&members[0].name), members.len() - 1),
        };
        let _ = writeln!(out, "| {offsets} | {name} | {} |", cell(correction));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Fails when a generated Markdown table has a row whose column count differs
    /// from its header.
    ///
    /// Adding a column to a row and forgetting the header renders as a broken table
    /// rather than an error, so it is worth checking rather than eyeballing.
    #[test]
    fn generated_tables_have_consistent_columns() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap_or(Path::new("."));
        let document = std::fs::read_to_string(root.join(DOC_PATH)).expect("document is readable");

        let columns = |line: &str| line.trim().trim_matches('|').split('|').count();
        let mut expected: Option<usize> = None;
        for (number, line) in document.lines().enumerate() {
            let line = line.trim();
            if !line.starts_with('|') {
                expected = None;
                continue;
            }
            // The dashed rule under a header sets the width for the rows that follow.
            if line.chars().all(|c| "|-: ".contains(c)) {
                expected = Some(columns(line));
                continue;
            }
            if let Some(want) = expected {
                assert_eq!(
                    columns(line),
                    want,
                    "{DOC_PATH} line {}: table row has {} columns, header has {want}",
                    number + 1,
                    columns(line)
                );
            }
        }
    }

    /// Fails when `docs/midi-spec.md` does not match the spec files.
    ///
    /// This is the safety net that keeps generated documentation honest: editing
    /// a spec file without regenerating turns `cargo test` red.
    #[test]
    fn generated_documentation_is_current() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap_or(Path::new("."));
        match run(root, true) {
            Ok(Outcome::Current) => {}
            Ok(Outcome::Stale) => panic!(
                "{DOC_PATH} is out of date with spec/. Run `cargo xtask docs` and commit the result."
            ),
            Err(message) => panic!("{message}"),
        }
    }
}
